_adapt_from_python: add fallback for default adapters
This fallback is needed so that ObjectAdaptationTests teardown
will correctly restore the default state. Otherwise, tests that
rely on the default state would fail as follows:

======================================================================
ERROR: test_CheckLargeInt (test_types.SqliteTypeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pyrqlite/extensions.py", line 163, in _adapt_from_python
    adapted = adapters[(type(value), sqlite3.PrepareProtocol)](value)
KeyError: (<class 'int'>, <class 'sqlite3.PrepareProtocol'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test/test_types.py", line 73, in test_CheckLargeInt
    self.cur.execute("insert into test(i) values (?)", (num,))
  File "pyrqlite/cursors.py", line 106, in execute
    operation = self._substitute_params(operation, parameters)
  File "pyrqlite/cursors.py", line 97, in _substitute_params
    subst.append(_adapt_from_python(parameters[i]))
  File "pyrqlite/extensions.py", line 173, in _adapt_from_python
    raise InterfaceError(e)
sqlite3.InterfaceError: (<class 'int'>, <class 'sqlite3.PrepareProtocol'>)

======================================================================
ERROR: test_CheckSmallInt (test_types.SqliteTypeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pyrqlite/extensions.py", line 163, in _adapt_from_python
    adapted = adapters[(type(value), sqlite3.PrepareProtocol)](value)
KeyError: (<class 'int'>, <class 'sqlite3.PrepareProtocol'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test/test_types.py", line 66, in test_CheckSmallInt
    self.cur.execute("insert into test(i) values (?)", (42,))
  File "pyrqlite/cursors.py", line 106, in execute
    operation = self._substitute_params(operation, parameters)
  File "pyrqlite/cursors.py", line 97, in _substitute_params
    subst.append(_adapt_from_python(parameters[i]))
  File "pyrqlite/extensions.py", line 173, in _adapt_from_python
    raise InterfaceError(e)
sqlite3.InterfaceError: (<class 'int'>, <class 'sqlite3.PrepareProtocol'>)