Connection.execute: don't call Cursor.__exit__ before return
This fixes the following ExtensionTests.test_CheckConnectionExecute
failure:

======================================================================
ERROR: test_CheckConnectionExecute (test_dbapi.ExtensionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_dbapi.py", line 772, in test_CheckConnectionExecute
    result = self.con.execute("select 5").fetchone()[0]
TypeError: 'NoneType' object is not subscriptable

Fixes: 0256d5fde135 ("Implicit cursor on Connection.execute")