EphemeralRqlited: improve error message for missing rqlited
When the rqlited binary is not found in PATH, include the 'rqlited'
filename in the exception message for python2.7. Otherwise, the
exception message is confusing:

$ python2.7 -c 'import subprocess; subprocess.Popen(["does-not-exist"])'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Reported-by: David Cole <david.cole@sohonet.com>