CursorTests.test_CheckExecuteWrongNoOfArgs2,3: expected failure
These tests currently produce the following errors because
Error is raised instead of ProgrammingError:

======================================================================
ERROR: test_CheckExecuteWrongNoOfArgs2 (test_dbapi.CursorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_dbapi.py", line 256, in test_CheckExecuteWrongNoOfArgs2
    self.cu.execute("insert into test(id) values (?)")
  File "pyrqlite/cursors.py", line 128, in execute
    raise Error(json.dumps(item))
sqlite3.Error: {"error": "not enough args to execute query: want 1 got 0"}

======================================================================
ERROR: test_CheckExecuteWrongNoOfArgs3 (test_dbapi.CursorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_dbapi.py", line 264, in test_CheckExecuteWrongNoOfArgs3
    self.cu.execute("insert into test(id) values (?)")
  File "pyrqlite/cursors.py", line 128, in execute
    raise Error(json.dumps(item))
sqlite3.Error: {"error": "not enough args to execute query: want 1 got 0"}